site_name: FastAPI Project Documentation
site_description: Documentation for the FastAPI Project
site_author: datascientest-fastAPI-project-group-25
repo_url: https://github.com/datascientest-fastAPI-project-group-25/fastAPI-project-docs

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - App:
    - Overview: app/README.md
  - Release:
    - Overview: release/README.md
  - Infrastructure:
    - Overview: infra/README.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

plugins:
  - search
